### ISSUE TITLE
README.md - Error

### ISSUE THREAD

**Issue by cleete** [GranderLab/miR34a_asRNA_project#1]
Change section into "### Installation" to:

1. Install [docker](https://www.docker.com) on your local computer.
2. Open R and install the R [devtools](https://github.com/hadley/devtools) package (if it is not already installed) with `install.packages('devtools')`.
3. Load the package with `library(devtools)`.
4. Download and install the miR34AasRNAproject package by entering `install_github('GranderLab/miR34a_asRNA_project')`. 

Further issue with installing miR34AasRNAproject package. See error message below: 

Downloading GitHub repo GranderLab/miR34a_asRNA_project@master
from URL https://api.github.com/repos/GranderLab/miR34a_asRNA_project/zipball/master
Installing miR34AasRNAproject
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/tn/2r9lfgsd1nq_wvg78t6_hzhr0000gn/T/RtmpFMjFbq/devtoolsa2ea70670742/GranderLab-miR34a_asRNA_project-0ff6f48'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library' --install-tests 

* installing *source* package ‘miR34AasRNAproject’ ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/Europe/Berlin'
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘liftr’
ERROR: lazy loading failed for package ‘miR34AasRNAproject’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/miR34AasRNAproject’
Installation failed: Command failed (1)
Warning message:
In strptime(x, fmt, tz = "GMT") :
  unknown timezone 'zone/tz/2017c.1.0/zoneinfo/Europe/Berlin'

Can be overcome by adding a line where to install.packages(liftr)

**Comment by jasonserviss** [comment]
Yeah, actually all the package dependencies need to be installed. I will fix that.

**Comment by jasonserviss** [comment]
This should be fixed now (commit 2057ebb).
