### ISSUE TITLE
plotFigure function - Invalid argument

### ISSUE THREAD

**Issue by cleete** [GranderLab/miR34a_asRNA_project#2]
After using the 'plotFigure('figure1a') function I got an error message as shown below:

invalid argument "figure1a_miR34aLocus" for t=figure1a_miR34aLocus: invalid reference format: repository name must be lowercase
See 'docker build --help'.
docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

**Comment by jasonserviss** [comment]
I think I know what this is... If I remember right docker doesn't like some of the folder names for some reason. I will have a look.

**Comment by jasonserviss** [comment]
I believe this is resolved now (commits 8298d2f1dc3c212e256ade053f4c29137b329b63 to 9a33fc7b099a999dd2588df89fcf2c325a68ac69). Let me know if there are any more issues.

note to self: added fileMap function to easier map between figures and files associated with them.
