### ISSUE TITLE
Not getting to the html after using plotFigure command

### ISSUE THREAD

**Issue by cleete** [GranderLab/miR34a_asRNA_project#3]
There is one issue with the plotFigure function, which is looking like this (this is a fraction of the entire process as it would be too long otherwise):

"* installing *source* package ‘miR34AasRNAproject’ ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘rlang’ 0.1.2 is already loaded, but >= 0.1.4 is required
ERROR: lazy loading failed for package ‘miR34AasRNAproject’
* removing ‘/usr/local/lib/R/site-library/miR34AasRNAproject’
Installation failed: Command failed (1)
 ---> a00d1fda8595
Removing intermediate container abe401ab98ef
Step 7/8 : RUN mkdir /liftrroot/
 ---> Running in 868e9a9fdb0e
 ---> 221673336e8e
Removing intermediate container 868e9a9fdb0e
Step 8/8 : WORKDIR /liftrroot/
 ---> 02c7f40d5eaf
Removing intermediate container dd478a9b5515
Successfully built 02c7f40d5eaf
Successfully tagged mir34a_locus:latest
Loading required package: methods

processing file: mir34a_locus.Rmd
  |.........                                                        |  14%
  ordinary text without R code

  |...................                                              |  29%
label: unnamed-chunk-1 (with options) 
List of 2
 $ echo   : logi FALSE
 $ message: logi FALSE

Loading tidyverse: ggplot2
Loading tidyverse: tibble
Loading tidyverse: tidyr
Loading tidyverse: readr
Loading tidyverse: purrr
Loading tidyverse: dplyr
Conflicts with tidy packages ----------------------------------------------
filter(): dplyr, stats
lag():    dplyr, stats
Quitting from lines 25-38 (mir34a_locus.Rmd) 
Error in .f(.x[[i]], ...) : 
  there is no package called 'miR34AasRNAproject'
Calls: render ... withCallingHandlers -> withVisible -> eval -> eval -> <Anonymous> -> .f

Execution halted"

It still opens a new tab in my browser but it doesn't show anything from it.

**Comment by jasonserviss** [comment]
Alright, I think I resolved this. 

Note to self: Can't find the version number of rlang in the rocker/tidyverse repo. Would have expected it to be 0.1.4 (which looks to be the current version) but potentially it is 0.1.2 and that is what caused the problem. Reduced the required version to 0.1.2 and everything seems to be working.
