### ISSUE TITLE
Issues with individual scripts for figures

### ISSUE THREAD

**Issue by cleete** [GranderLab/miR34a_asRNA_project#4]
I think there is a general issue with the figure scripts when I knit them, such as the one below:

for figure 1a:
cannot open URL 'https://github.com/GranderLab/miR34a_asRNA_project/raw/master/inst//figure1a_miR34aLocus/miR34aLocus_hg38.png': HTTP status was '404 Not Found'
(in this case the html opens but the image doesn't appear just a question mark)

or for figure 2a: 
Quitting from lines 104-149 (figure2a_HCT116p53null.Rmd) 
Error in readRDS(path) : 
  cannot open the connection to 'https://github.com/GranderLab/miR34a_asRNA_project/raw/master/data/figure2a_HCT116p53null.rds'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> read_rds -> readRDS
Execution halted

or for figure 2b:
Quitting from lines 102-152 (figure2b_HctHekDox.Rmd) 
Error in readRDS(path) : 
  cannot open the connection to 'https://github.com/GranderLab/miR34a_asRNA_project/raw/master/data/figure2b_HctHekDox.rds'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> read_rds -> readRDS
Execution halted

or for figure 3a:
Quitting from lines 172-254 (figure3a_stableLineExpression.Rmd) 
Error in readRDS(path) : 
  cannot open the connection to 'https://github.com/GranderLab/miR34a_asRNA_project/raw/master/data/figure3a_stableLineExpression.rds'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> read_rds -> readRDS
Execution halted

**Comment by jasonserviss** [comment]
This is related to issue #3 I believe. The output from the install in issue #3 shows that you did not manage to successfully install the latest package version and that is the reason you are getting the error shown in this issue. I will close this for now and you can re-open or comment on the same issue if the problem persists. The commands that you show giving an error above work fine on my computer with the latest package version...
